name: test

on:
  push:

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: install dependencies
        run: cd tests; npm install

      - name: Run tests
        run: cd tests; ./run_tests.sh
